version: '3.0'

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "85:80"
    depends_on:
      - php
    volumes:
      - ./logs:/var/log/nginx
      - ./src:/var/www/html
    networks:
      - default
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      # иначе сервер в контейнере не видит содержимое папки, хз почему
      - ./src/vendor:/var/www/html/vendor
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=services
      - MYSQL_ROOT_PASSWORD=8JJxJHl!69TEv#D
    networks:
      - backend
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "86:80"
    environment:
      - LETSENCRYPT_HOST=phpmyadmin.pstuffapp.com
      - LETSENCRYPT_EMAIL=absorber000@gmail.com
      - PMA_HOST=mysql
    networks:
      - default
      - frontend
      - backend


networks:
  default:
    external:
      name: nginxproxy_proxy
  frontend:
  backend:
